CONFIG_MCUX_ELS_PKC=y
CONFIG_WOLFSSL=y
CONFIG_WOLFSSL_BUILTIN=y
CONFIG_WOLFSSL_CRYPTO_ONLY=y
CONFIG_WOLFSSL_ELS_PKC=y
CONFIG_MAIN_STACK_SIZE=49152
CONFIG_PRINTK=y
CONFIG_POSIX_SYSTEM_INTERFACES=y
CONFIG_POSIX_TIMERS=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_WOLFSSL_RSA=y
CONFIG_WOLFSSL_CURVE25519=y
CONFIG_WOLFSSL_ECC_384=y
CONFIG_WOLFSSL_ECC_521=y
CONFIG_WOLFSSL_ECC_320=y
CONFIG_WOLFSSL_ECC_512=y
CONFIG_WOLFSSL_ECC_KOBLITZ=y
CONFIG_WOLFSSL_ECC_BRAINPOOL=y
