#!/bin/bash
# Audit Doxygen coverage for wolfssl/ and wolfssl/wolfcrypt/ headers
# (excluding wolfssl/wolfcrypt/port/ and wolfssl/openssl/).
#
# For each source header, extract WOLFSSL_API function names and compare
# against the corresponding doc file in doc/dox_comments/header_files/.
#
# Run from anywhere; paths are resolved relative to this script.
# Writes COVERAGE.md and COVERAGE_DETAIL.md into doc/dox_comments/.

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WOLFSSL_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DOC_DIR="$WOLFSSL_ROOT/doc/dox_comments/header_files"
OUT="$WOLFSSL_ROOT/doc/dox_comments/COVERAGE.md"

# Extract WOLFSSL_API function names from a source header.
extract_src_names() {
    local f="$1"
    grep -h -o 'WOLFSSL_API[^;]*;' "$f" 2>/dev/null \
        | tr '\n' ' ' \
        | sed 's/WOLFSSL_API/\nWOLFSSL_API/g' \
        | sed -n 's/.*WOLFSSL_API[^(]*[[:space:]*]\([A-Za-z_][A-Za-z0-9_]*\)[[:space:]]*(.*/\1/p' \
        | sort -u
}

# Extract function names from a doc file. Doc files contain Doxygen
# comment blocks followed by bare prototypes (no WOLFSSL_API prefix).
# Look for lines outside comments that match "ident ( ... );".
extract_doc_names() {
    local f="$1"
    # Strip Doxygen block comments, then extract function declarations.
    # A declaration is a single statement ending in ';' that contains '('.
    # We grab the identifier immediately before the '('.
    awk '
        BEGIN { in_block=0; buf="" }
        {
            line=$0
            # remove block comments inline
            while (match(line, /\/\*/)) {
                pre=substr(line,1,RSTART-1)
                rest=substr(line,RSTART+2)
                end=index(rest, "*/")
                if (end > 0) {
                    line = pre substr(rest, end+2)
                } else {
                    # comment continues to next line
                    line = pre
                    in_block = 1
                    break
                }
            }
            if (in_block) {
                end = index($0, "*/")
                if (end > 0) {
                    in_block = 0
                    line = substr($0, end+2)
                } else {
                    next
                }
            }
            # strip line comments
            sub(/\/\/.*$/, "", line)
            if (line ~ /^[[:space:]]*$/) next
            buf = buf " " line
            if (index(buf, ";") > 0) {
                print buf
                buf = ""
            }
        }
    ' "$f" \
        | grep -oE '[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\(' \
        | sed 's/[[:space:]]*($//' \
        | grep -vE '^(if|while|for|switch|return|sizeof|typedef|struct|enum|union)$' \
        | sort -u
}

# Headers that are intentionally not user-facing (internal glue / math
# internals / CPU detection / RNG plumbing). Excluded from the coverage
# table so the report reflects the real public-API gap.
INTERNAL_SKIP=(
    "wolfssl/wolfcrypt/cpuid.h"
    "wolfssl/wolfcrypt/rng_bank.h"
    "wolfssl/wolfcrypt/sp_int.h"
    "wolfssl/wolfcrypt/wolfmath.h"
)

is_internal() {
    local rel="$1"
    local s
    for s in "${INTERNAL_SKIP[@]}"; do
        [ "$s" = "$rel" ] && return 0
    done
    return 1
}

{
    echo "# Doxygen Coverage Report"
    echo
    echo "Generated by doc/check_coverage.sh on $(date +%Y-%m-%d)."
    echo
    echo "Scope: wolfssl/*.h + wolfssl/wolfcrypt/*.h (excluding port/ and openssl/)."
    echo
    echo "Method: extract function names declared with WOLFSSL_API in each source"
    echo "header and check that the corresponding doc file under"
    echo "\`doc/dox_comments/header_files/\` declares the same function name."
    echo
    echo "Headers in \`INTERNAL_SKIP\` (see top of \`check_coverage.sh\`) are omitted"
    echo "from the table because they expose only internal plumbing:"
    for s in "${INTERNAL_SKIP[@]}"; do
        echo "- \`$s\`"
    done
    echo
    echo "| Header | WOLFSSL_API count | Documented | Missing | Doc file |"
    echo "|---|---|---|---|---|"
} > "$OUT"

HEADERS=$(find "$WOLFSSL_ROOT/wolfssl" -maxdepth 2 -name '*.h' \
    -not -path '*/openssl/*' \
    -not -path '*/port/*' \
    | sort)

declare -a MISSING_DOC_FILES=()
declare -a TIER2_FILES=()
TOTAL_API=0
TOTAL_DOCUMENTED=0
TOTAL_MISSING=0

# Per-file missing-name detail goes into a second file
DETAIL="$WOLFSSL_ROOT/doc/dox_comments/COVERAGE_DETAIL.md"
{
    echo "# Doxygen Coverage — Missing Function Detail"
    echo
    echo "Lists the WOLFSSL_API function names declared in each source header"
    echo "but not found in the corresponding doc file."
    echo
} > "$DETAIL"

for h in $HEADERS; do
    base=$(basename "$h")
    rel=${h#$WOLFSSL_ROOT/}
    is_internal "$rel" && continue
    src_names=$(extract_src_names "$h")
    src_count=$(echo "$src_names" | grep -c . || true)

    [ "$src_count" = "0" ] && continue

    doc="$DOC_DIR/$base"
    if [ ! -f "$doc" ]; then
        echo "| \`$rel\` | $src_count | 0 | $src_count | **MISSING** |" >> "$OUT"
        MISSING_DOC_FILES+=("$rel ($src_count APIs)")
        TOTAL_API=$((TOTAL_API + src_count))
        TOTAL_MISSING=$((TOTAL_MISSING + src_count))
        {
            echo "## \`$rel\` (no doc file)"
            echo
            echo "$src_names" | sed 's/^/- /'
            echo
        } >> "$DETAIL"
        continue
    fi

    doc_names=$(extract_doc_names "$doc")
    missing_names=$(comm -23 <(echo "$src_names") <(echo "$doc_names"))
    missing=$(echo "$missing_names" | grep -c . || true)
    documented=$((src_count - missing))

    echo "| \`$rel\` | $src_count | $documented | $missing | \`doc/dox_comments/header_files/$base\` |" >> "$OUT"

    TOTAL_API=$((TOTAL_API + src_count))
    TOTAL_DOCUMENTED=$((TOTAL_DOCUMENTED + documented))
    TOTAL_MISSING=$((TOTAL_MISSING + missing))

    if [ "$missing" -gt 0 ]; then
        TIER2_FILES+=("$rel:$missing")
        {
            echo "## \`$rel\` ($missing missing)"
            echo
            echo "$missing_names" | sed 's/^/- /'
            echo
        } >> "$DETAIL"
    fi
done

{
    echo
    echo "## Totals"
    echo
    echo "- Total WOLFSSL_API functions: $TOTAL_API"
    echo "- Documented: $TOTAL_DOCUMENTED"
    echo "- Missing: $TOTAL_MISSING"
    echo
    echo "## Tier 1 — Headers with no doc file"
    echo
    if [ ${#MISSING_DOC_FILES[@]} -eq 0 ]; then
        echo "_None._"
    else
        for f in "${MISSING_DOC_FILES[@]}"; do
            echo "- $f"
        done
    fi
    echo
    echo "## Tier 2 — Doc file exists but functions missing"
    echo
    if [ ${#TIER2_FILES[@]} -eq 0 ]; then
        echo "_None._"
    else
        for f in "${TIER2_FILES[@]}"; do
            echo "$f"
        done | sort -t: -k2 -nr | while IFS=: read -r path n; do
            echo "- $path — $n missing"
        done
    fi
    echo
    echo "See \`COVERAGE_DETAIL.md\` for the per-file list of missing function names."
} >> "$OUT"

echo "Wrote $OUT"
echo "Wrote $DETAIL"
